[features]
resolution = true
skip-lint = false

[programs.localnet]
durian_trust = "11111111111111111111111111111111"

[programs.devnet]
durian_trust = "11111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm test"
